os: linux
language: python
python: 3.6

env:
  global:
    # Doctr deploy key for hhslepicka/pydm-tutorial
    - secure: "tjM4pU+b40lw2UlRJNrBdE99Evmv9vn2wE5DTrIkeYXD43fytcQKm/Arf/jKfAJxifHQIBE6mGxiNooBB3CqjVHZzDuN2eS0t42D07jDjNLPMRvlP6S7U0wLdRb8HKgfOGFA/BQxScklfM3dM281zhrV9/GGNXsJ3Ah5QB9oyF9A27eNLnTPaqvqfGfmwZ/dEzB+6oL0KYIRZgxvKMGsEcZVfe3llZjQms6tnwr37NXTKjHWKACpYDR6mPNj4IgRzvkvOIdGIaSMqX4ANoQrkzW+y8I9L+SeOnPt81sMCgZgg13lZ36oSXU4/+vLhow63vN69sWzmVaVA84JDQQ0kTD9J27kfg47awEmn8TOSInLM78HseZZndNeWhgkfsNgb9hgI6yrTmnqm3otmT/XT2nC70x0ja7W/CWASHzc+Poc+A26PiMzf1OyXRX/z7pi7opJYsjFyUicO9VPNRR5U8NK/ZUSQYoPOMSDy3M9qR6sCuLPqJof7J+7MAohV1SvPn+gmas8u7Fx6wS3fsojMNk9h+E3yTYsGI9b6uV0ydGu3AXrxZ3Xqf31PFUVYs4hatpMiO6lqV6GtiVyfpK6eHoDvBCSgIEZarqpb4S68IbywXIFz1HocStvXOTqX3BIkc34edpSw1Oys7u1iVSsYOfnSIhoXfVzbgErXeZXx7U="

script:
  #Build docs
  - set -e
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY_SLACLAB_PYDM_TUTORIAL" ]]; then
      pip install -r docs-requirements.txt
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy . --built-docs docs/build/html --deploy-branch-name gh-pages
    fi
